variables:
  CI_IMAGE: "gcr.io/pledra-1/product-configurator"
  ODOO_MINOR: "13.0"
  PSQL_VERSION: "11.8"

include:
  - project: 'pledra/pledra-doodba-scaffolding'
    file: '/templates/.gitlab-ci-template.yml'
