variables:
  CI_IMAGE: "gcr.io/pledra-1/product-configurator"
  CI_IMAGE_TAG: "11.0-${CI_COMMIT_SHA}"
  GCLOUD_PROJECT: "pledra-1"
  ODOO_MINOR: "11.0"
  ODOO_STAGING_BRANCH: "11.0-staging"

include:
  - project: 'pledra/pledra-doodba-scaffolding'
    file: '/templates/.gitlab-ci-template.yml'

